[package]
name = "advent_of_code_template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.15.2"
regex = "1.11.1"
log = "0.4.17"
env_logger = "0.10.0"